package com.example.bhukkad;

import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import com.example.bhukkad.databinding.ActivityStaffDashboardBinding;
import java.util.ArrayList;
import java.util.List;
import androidx.lifecycle.ViewModelProvider;

public class StaffDashboardActivity extends AppCompatActivity {

    // This "Binding" class is automatically generated by Android Studio
    // based on your XML filename (e.g., activity_staff_dashboard.xml)
    private ActivityStaffDashboardBinding binding;
    private OrderAdapter adapter;


    private DashboardViewModel viewModel;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityStaffDashboardBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        // Initialize the ViewModel
        viewModel = new ViewModelProvider(this).get(DashboardViewModel.class);

        // Start "Watching" the data
        observeViewModel();
        setupRecyclerView();
        setupClickListeners();
    }

    private void observeViewModel() {
        // When revenue changes in ViewModel, update the card text
        viewModel.getRevenue().observe(this, amount -> {
            binding.revenueTextId.setText(amount);
        });

        viewModel.getOrdersToday().observe(this, count -> {
            binding.orderCountId.setText(String.valueOf(count));
        });
    }

    private void setupRecyclerView() {
        // Just initialize the adapter with an empty list first
        adapter = new OrderAdapter(new ArrayList<>());
        binding.rvOrders.setLayoutManager(new LinearLayoutManager(this));
        binding.rvOrders.setAdapter(adapter);

        // Now, tell the Activity to watch the orders in the ViewModel
        viewModel.getOrders().observe(this, newOrders -> {
            // When the list changes, update the adapter
            adapter.updateList(newOrders);
        });

        // Finally, tell the ViewModel to load the data
        viewModel.loadMockOrders();
    }

    private void setupClickListeners() {
        // Tapping the Incoming Orders card
        binding.btnIncoming.setOnClickListener(v -> {
            // For now, just a message. Later, start a new Activity.
            android.widget.Toast.makeText(this, "Opening Incoming Orders...", android.widget.Toast.LENGTH_SHORT).show();
        });

        // Tapping the Menu Management card
        binding.btnMenuManagement.setOnClickListener(v -> {
            android.widget.Toast.makeText(this, "Opening Menu Editor...", android.widget.Toast.LENGTH_SHORT).show();
        });

        // Tapping the Revenue Card could show a detailed report
        binding.cardRevenue.setOnClickListener(v -> {
            // Example: Changing data dynamically to see the ViewModel in action
            viewModel.updateRevenue("₹ 1,250.00");
        });
    }
}